### DISCUSSION TITLE
Recon shows Zero DataNodes

### DISCUSSION THREAD

**Discussion by jcasse** [apache/ozone#5842] [General]
I'm trying out Ozone in Minikube using `ozone-1.3.0/kubernetes/examples/minikube`.
The Minikube example does not include Recon, so I added it by creating the corresponding Kubernetes manifests similar to the other components.
After deploying Ozone, I accessed the Recon UI by executing `minikube service recon-public`.

After adding some data, Recon shows DiskUsage (image attached), but zero DataNodes (image attached).
![disk-usage](https://github.com/apache/ozone/assets/6751943/3ccf63e4-fb57-41e2-a5ce-85489f4292bd)
![overview](https://github.com/apache/ozone/assets/6751943/79bfa9e0-710d-4997-8399-7583ab762edd)

I have attached an archive file with my Kubernetes manifests.
[minikube.zip](https://github.com/apache/ozone/files/13729972/minikube.zip)

My added/modified files look like this:

`kustomization.yaml`
```
resources:
- config-configmap.yaml
- datanode-service.yaml
- datanode-statefulset.yaml
- om-service.yaml
- om-statefulset.yaml
- s3g-service.yaml
- s3g-statefulset.yaml
- scm-service.yaml
- scm-statefulset.yaml
- recon-service.yaml
- recon-statefulset.yaml
- datanode-public-service.yaml
- om-public-service.yaml
- s3g-public-service.yaml
- scm-public-service.yaml
- recon-public-service.yaml
```

`config-configmap.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  OZONE-SITE.XML_hdds.datanode.dir: /data/storage
  OZONE-SITE.XML_ozone.scm.datanode.id.dir: /data
  OZONE-SITE.XML_ozone.metadata.dirs: /data/metadata
  OZONE-SITE.XML_ozone.scm.block.client.address: scm-0.scm
  OZONE-SITE.XML_ozone.om.address: om-0.om
  OZONE-SITE.XML_ozone.scm.client.address: scm-0.scm
  OZONE-SITE.XML_ozone.scm.names: scm-0.scm
  OZONE-SITE.XML_hdds.scm.safemode.min.datanode: "3"
  OZONE-SITE.XML_ozone.datanode.pipeline.limit: "1"
  OZONE-SITE.XML_ozone.recon.db.dir: /data/recon/db
  OZONE-SITE.XML_ozone.recon.om.db.dir: /data/recon/om/db
  OZONE-SITE.XML_ozone.recon.scm.db.dir: /data/recon/scm/db
  LOG4J.PROPERTIES_log4j.rootLogger: INFO, stdout
  LOG4J.PROPERTIES_log4j.appender.stdout: org.apache.log4j.ConsoleAppender
  LOG4J.PROPERTIES_log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
  LOG4J.PROPERTIES_log4j.appender.stdout.layout.ConversionPattern: '%d{yyyy-MM-dd
    HH:mm:ss} %-5p %c{1}:%L - %m%n'
```

`recon-public-service.yaml`

```
apiVersion: v1
kind: Service
metadata:
  name: recon-public
spec:
  ports:
  - port: 9888
    name: ui
  selector:
    app: ozone
    component: recon
  type: NodePort
```

`recon-service.yaml`

```
apiVersion: v1
kind: Service
metadata:
  name: recon
spec:
  ports:
  - port: 9888
    name: ui
  clusterIP: None
  selector:
    app: ozone
    component: recon
```

`recon-statefulset.yaml`

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recon
  labels:
    app.kubernetes.io/component: ozone
spec:
  selector:
    matchLabels:
      app: ozone
      component: recon
  serviceName: recon
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: recon
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: recon
        image: 'apache/ozone:1.3.0'
        args:
        - ozone
        - recon
        livenessProbe:
          httpGet:
            path: /
            port: 9888
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
```
